export const vidAuditForm1 = {
  column: [
    {
      disabled: true,
      label: "是否违规",
      prop: "type",
      type: "radio",
      labelSuffix: "：",
      labelPosition: "right",
      labelWidth: 140,
      value: "99",
      span: 24,
      display: true,
      dicData: [
        {
          label: "是",
          value: "40",
        },
        {
          label: "否",
          value: "99",
        },
      ],
    },
    {
      disabled: true,
      type: "select",
      label: "视频推荐等级",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "pushLevel",
    },
    {
      disabled: true,
      type: "cascader",
      prop: "classifyId",
      label: "视频标签",
      span: 12,
      labelWidth: 140,
      labelPosition: "right",
      showAllLevels: false,
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "blur",
        },
      ],
      dicData: [],
      separator: "/",
      props: {
        label: "classifyName",
        value: "id",
        children: "childClassifyList",
      },
    },
    {
      disabled: true,
      type: "select",
      label: "视频观看权限",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "watchLevel",
    },
    {
      disabled: true,
      type: "select",
      label: "视频下载权限",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "download",
    },
    {
      disabled: true,
      type: "select",
      multiple: true,
      label: "视频标签",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      allowCreate: true,
      filterable: true,
      value: [],
      defaultFirstOption: true,
      rules: [
        {
          required: true,
          message: "至少有一项选中标签!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 24,
      display: true,
      props: {
        label: "labelName",
        value: "id",
      },
      prop: "labelIdList",
    },
    {
      disabled: true,
      type: "select",
      prop: "refuseReason",
      props: {
        label: "refuseReason",
        value: "refuseReason",
      },
      display: false,
      label: "未通过原因",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      span: 12,
    },
    {
      disabled: true,
      type: "input",
      display: false,
      label: "违规内容时间段",
      labelWidth: 140,
      labelPosition: "right",
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      prop: "unContent",
    },
  ],
  labelWidth: 120,
  clearExclude: ["type"],
  gutter: 0,
  menuBtn: false,
  submitBtn: false,
  submitText: "提交",
  emptyBtn: false,
  emptyText: "重置",
  menuPosition: "center",
};
export const vidAuditForm = {
  column: [
    {
      label: "是否违规",
      prop: "type",
      type: "radio",
      labelSuffix: "：",
      labelPosition: "right",
      labelWidth: 140,
      value: "99",
      span: 24,
      display: true,
      dicData: [
        {
          label: "是",
          value: "40",
        },
        {
          label: "否",
          value: "99",
        },
      ],
    },
    {
      type: "select",
      label: "视频推荐等级",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "pushLevel",
    },
    {
      type: "cascader",
      prop: "classifyId",
      label: "视频标签",
      span: 12,
      labelWidth: 140,
      labelPosition: "right",
      showAllLevels: false,
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "blur",
        },
      ],
      dicData: [],
      separator: "/",
      props: {
        label: "classifyName",
        value: "id",
        children: "childClassifyList",
      },
    },
    {
      type: "select",
      label: "视频观看权限",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "watchLevel",
    },
    {
      type: "select",
      label: "视频下载权限",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      display: true,
      props: {
        label: "dictionaryKey",
        value: "dictionaryValue",
      },
      prop: "download",
    },
    {
      type: "select",
      multiple: true,
      label: "视频标签",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      allowCreate: true,
      filterable: true,
      value: [],
      defaultFirstOption: true,
      // rules: [
      //   {
      //     required: true,
      //     message: "至少有一项选中标签!",
      //     trigger: "change",
      //   },
      // ],
      cascaderItem: [],
      span: 24,
      display: true,
      props: {
        label: "labelName",
        value: "id",
      },
      prop: "labelIdList",
    },
    {
      type: "select",
      prop: "refuseReason",
      props: {
        label: "refuseReason",
        value: "refuseReason",
      },
      display: false,
      label: "未通过原因",
      labelWidth: 140,
      labelPosition: "right",
      dicData: [],
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      span: 12,
    },
    {
      type: "input",
      display: false,
      label: "违规内容时间段",
      labelWidth: 140,
      labelPosition: "right",
      rules: [
        {
          required: true,
          message: "不能为空!",
          trigger: "change",
        },
      ],
      cascaderItem: [],
      span: 12,
      prop: "unContent",
    },
  ],
  labelWidth: 120,
  clearExclude: ["type"],
  gutter: 0,
  menuBtn: true,
  submitBtn: true,
  submitText: "提交",
  emptyBtn: true,
  emptyText: "重置",
  menuPosition: "center",
};
export const titleOptions1 = {
  column: [
    {
      type: "input",
      label: "视频标题",
      span: 24,
      display: true,
      prop: "videoTitle",
      required: true,
      disabled: true,
    },
    {
      type: "textarea",
      label: "视频描述",
      span: 24,
      display: true,
      prop: "videoIntroduce",
      minRows: 16,
      maxRows: 16,
      required: true,
      disabled: true,
    },
  ],
  labelPosition: "right",
  labelSuffix: ":",
  labelWidth: 100,
  gutter: 0,
  menuBtn: false,
  submitBtn: false,
  submitText: "提交",
  emptyBtn: false,
  emptyText: "清空",
  menuPosition: "center",
};
export const titleOptions = {
  column: [
    {
      type: "input",
      label: "视频标题",
      span: 24,
      display: true,
      prop: "videoTitle",
      required: true,
      rules: [
        {
          required: true,
          message: "视频标题不能为空!",
        },
      ],
    },
    {
      type: "textarea",
      label: "视频描述",
      span: 24,
      display: true,
      prop: "videoIntroduce",
      minRows: 10,
      maxRows: 16,
      required: true,
      readonly: false,
    },
  ],
  labelPosition: "right",
  labelSuffix: ":",
  labelWidth: 100,
  gutter: 0,
  menuBtn: false,
  submitBtn: true,
  submitText: "提交",
  emptyBtn: true,
  emptyText: "清空",
  menuPosition: "center",
};
