stages:
  - name: nodejs编译
    steps:
      - runScriptConfig:
          image: registry.cn-zhangjiakou.aliyuncs.com/ds_zhouqiang/node:14.17-alpine3.14
          shellScript: |-
            # 编译
            npm install cnpm -g --registry=https://registry.npm.taobao.org
            cnpm pre
            cnpm i
            cnpm test
            ls -la
  - name: 构建镜像
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: ds-admin-web:${CICD_EXECUTION_SEQUENCE}
  - name: 部署
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
timeout: 60
notification: {}
